const errdict = {
    "0": "no error",
    "16000": "The trading system is not available for trading.",
    "16001": "Invalid User Type OR Reset User Password not requested by Corporate manager",
    "16003": "Erroneous transaction code received.",
    "16004": "User already signed on.",
    "16006": "Invalid Box/User sign-on, please try again.",
    "16007": "Signing on to the trading system is restricted. Please try later on.",
    "16012": "Invalid symbol/series",
    "16013": "Invalid order number",
    "16015": "Invalid trade cancel request.",
    "16035": "Security is unavailable for trading at this time. Please try later.",
    "16041": "Trading Member does not exist in the system",
    "16042": "Dealer does not exist in the system",
    "16050": "Trade modification request rejected as end of the day processing started.",
    "16052": "When Preopen trade cancel request is rejected OR BOVL/UOVL Limits not allowed to be set as unlimited OR BOVL update not requested by Corporate Manager OR Inconsistent data for BOVL update OR Branch Manager not allowed UOVL update for self/CM/other BM/users of other branch. OR Branch Manager not allowed Dealer Limit update for self. OR User Unlock Request not requested by Corporate Manager OR User Unlock Request not allowed for Corporate Manager OR User level COL disabled",
    "16053": "Your password has expired, must be changed.",
    "16054": "Branch does not exist in the system. OR Inconsistent data for UOVL update",
    "16056": "Program error.",
    "16060": "Modified/Cancelled order not found",
    "16063": "Requested status change not allowed",
    "16070": "Data has not changed",
    "16098": "Invalid trader ID for buyer.",
    "16099": "Invalid trader ID for seller.",
    "16100": "Your system version has not been updated.",
    "16104": "System could not complete your transaction - ADMIN notified.",
    "16115": "Order Modification/ Cancellation rejected by the system.",
    "16123": "System not able to complete your request. Please try again.",
    "16134": "This Dealer is disabled. Please call the Exchange.",
    "16145": "Security is not eligible to trade in Preopen.",
    "16148": "Invalid Dealer ID entered.",
    "16154": "Invalid Trader ID entered.",
    "16169": "Order priced ATO cannot be entered when a security is open.",
    "16197": "Order Entry or Modification not allowed in preopen.",
    "16233": "Proprietary requests cannot be made for participant.",
    "16247": "Invalid price in the price field.",
    "16251": "Trade modification with different quantities is received.",
    "16252": "Cancelled the trade modify request",
    "16260": "Record is there in master file but delete flag is set",
    "16264": "The member has already been deleted.",
    "16273": "Record does not exist.",
    "16278": "The markets have not been opened for trading.",
    "16279": "The security has not yet been admitted for trading.",
    "16280": "The security has matured.",
    "16281": "The security has been expelled.",
    "16282": "The order quantity is greater than the issued capital.",
    "16283": "The order price is not multiple of the tick size.",
    "16284": "The order price is out of the day's price range.",
    "16285": "The broker is not active.",
    "16300": "System is in a wrong state to make the requested change.",
    "16303": "Request denied. Pending auctions.",
    "16307": "The order is canceled due to quantity freeze",
    "16308": "The order is canceled due to price freeze",
    "16310": "AON volume not enough",
    "16311": "The Solicitor period for the Auction is over.",
    "16312": "The Competitor period for the Auction is over.",
    "16313": "The Auction period will cross Market Close time.",
    "16314": "The Auction cannot be cancelled.",
    "16315": "The limit price is worse than the trigger price",
    "16316": "The trigger price is not a multiple of tick size.",
    "16317": "AON attribute not allowed.",
    "16318": "MF attribute not allowed.",
    "16319": "AON attribute not allowed at security level.",
    "16320": "MF attribute not allowed at security level.",
    "16321": "MF quantity is greater than Disclosed quantity.",
    "16322": "MF quantity is not a multiple of regular lot.",
    "16323": "MF quantity is greater than Original quantity.",
    "16324": "Disclosed quantity is greater than Original quantity.",
    "16325": "Disclosed quantity is not a multiple of regular lot.",
    "16326": "GTD is greater than that specified at System",
    "16327": "Quantity is greater than Regular lot size.",
    "16328": "Quantity is not a multiple of regular lot.",
    "16329": "Trading Member not permitted in the market",
    "16330": "Security is suspended.",
    "16332": "Remaining passive order has to be cancelled.",
    "16333": "Branch Order Value Limit is exceeded.",
    "16343": "The order to be cancelled has changed.",
    "16344": "The order cannot be cancelled",
    "16345": "Initiator order cannot be cancelled.",
    "16346": "Order cannot be modified.",
    "16348": "Trading is not allowed in this market.",
    "16357": "Order entered for negotiated trade is cancelled.",
    "16363": "New status requested should not be same as existing one.",
    "16369": "The security status is preopen.",
    "16372": "Order entry not allowed for user as it is of inquiry type.",
    "16379": "The broker is not allowed to enter soliciting orders.",
    "16383": "Trading in this auction is finished.",
    "16387": "Security is not allowed to trade in this market.",
    "16388": "When Preopen unmatched orders are cancelled by the system after preopen session ends. When normal market unmatched orders are cancelled by the system if order collection phase is planned after circuit hit.",
    "16392": "Turnover limit not provided. Please contact Exchange.",
    "16395": "The Negotiated trades cannot be cancelled",
    "16400": "DQ has exceeded limit set in control.",
    "16403": "You are trying to sign on from a different location. Sign on is not allowed.",
    "16404": "Order is cancelled due to freeze admin suspension.",
    "16411": "Pro-client can be either Pro or Client only.",
    "16412": "New volume should be less than the traded volume.",
    "16413": "Requested by can be BUY or SELL or BOTH.",
    "16414": "Invalid combination of book type and instructions (order_type).",
    "16415": "Invalid combination of MF / AON / Disclosed Volume.",
    "16416": "Invalid counter broker Id.",
    "16417": "Number of NNF requests exceeded.",
    "16418": "Order entered has invalid data.",
    "16419": "Cancelled trade cancel request.",
    "16420": "Alpha char must be the same as first two chars of symbol.",
    "16421": "Only control can initiate auctions, not trader.",
    "16422": "Book type should be between 1(RL) and 7(AU).",
    "16423": "Invalid trigger price entered.",
    "16424": "Message length is invalid.",
    "16425": "Participant does not exist.",
    "16426": "Participant and volume cannot be changed simultaneously.",
    "16427": "Trade modification rejected due to broker suspension",
    "16430": "Invalid auction inquiry request.",
    "16431": "Invalid Account in the Account field",
    "16436": "The order value limit has exceeded",
    "16439": "DQ Orders are not allowed in preopen.",
    "16440": "Order Entry is not allowed in preopen for the series.",
    "16441": "ST Orders are not allowed in preopen.",
    "16442": "The current placed order’s value is more than users order value limit",
    "16448": "Difference between limit price and trigger price is beyond permissible range",
    "16450": "Account number is mandatory in Account field",
    "16473": "Only board lot market orders are allowed in Closing Session.",
    "16482": "The order has been cancelled as security has been suspended",
    "16483": "The order has been cancelled as participant has been suspended",
    "16493": "Functionality not available for Inquiry user",
    "16530": "Users buy order value limit has exceeded.",
    "16531":  "The order value limit for the sell quantity has exceeded its limit",
    "16532": "Branch buy order limit has been exceeded",
    "16533": "Branch sell order limit has been exceeded",
    "16534": "No buyback running for that security",
    "16535": "Order partially rejected. Remaining order quantity specified rejected due to system error.",
    "16536": "Quick Cancel request rejected due to system error. Retry Quick Cancel Request",
    "16560": "Not allowed to reset user’s own login session",
    "16562": "Requested user is already signed off",
    "16563": "No privilege to execute functionality",
    "16567": "This error code will be returned when a Close out order goes into freeze.",
    "16568": "This error code is returned when a Close out order entry is not allowed.",
    "16569": "This error code is returned when a Close out order is rejected by the system.",
    "16571": "This error code will be returned when a user under a broker in 'Close out' state tries to modify Trade.",
    "16573": "Message length is invalid.",
    "16576": "Maximum UOVL exceeded",
    "16577": "Maximum BOVL exceeded",
    "16588": "User does not exist",
    "16592": "Order Entry is not allowed",
    "16597": "Order entry / Modification rejected by the Exchange",
    "16598": "Order Entry is not allowed",
    "16600": "The order value has exceeded maximum permissible limit",
    "16601": "Request Rejected by the exchange",
    "16603": "Market order not allowed in Block Trade session",
    "16604": "Disclosed Quantity (DQ) order not allowed in closing session",
    "16606": "Client order not allowed for market maker user",
    "16750": "Order Limit exceeds the set User Order Value Limit",
    "16752": "User already unlocked",
    "16753": "Duplicate user unlock request",
    "16761": " The account is debarred from trading (New error code defined for order entry/Modification due to debarred Client.)",
    "16778": "Password set is not in lines of the password policy",
    "17015": "Status change not allowed. User should be Dealer/Branch Manager/Inquiry",
    "17101": "The packet has invalid transaction code OR Packet has invalid data",
    "17102": "Heart Beat not received",
    "17104": "Invalid Box Id",
    "17105": "Sequence number mismatch found",
    "17106": "Box Rate has been exceeded by the Member",
    "17017": "Order Cancelled due to Voluntary Closeout.",
    "17022": "Number for active users in branch exceeded",
    "17080": "The order could have resulted in self-trade.",
    "17142": "Maximum user login allowed per box has been exceeded",
    "17177": "Invalid PAN Id",
    "17179": "Invalid Algo Id",
    "17180": "Invalid value in the Reserved Filler field",
    "17182": "Security not traded. Market order not allowed.",
    "17183": "Order could have resulted in trade beyond mark-up price.",
    "17184": "Order rejected as user has NO trading rights",
    "19028": "Checksum verification failed at Gateway Router.",
    "19029": "Multiple GR_QUERY request received.",
    "16397": "Modifying Auction Order not allowed",
    "19030": "Encryption Flag Mismatch",
    "19031": "MD5 Checksum Failed"
}

const transdict = {
    "1110": "INDUSTRY_INDEX_DLOAD_IN",
    "1111": "INDUSTRY_INDEX_DLOAD_OUT",
    "1600": "SYSTEM_INFORMATION_IN",
    "1601": "SYSTEM_INFORMATION_OUT",
    "1833": "MARKET_STATS_REPORT_DATA",
    "2000": "BOARD_LOT_IN",
    "2001": "BOARD_LOT_OUT",
    "2008": "NEG_ORDER_TO_BL",
    "2009": "NEG_ORDER_BY_CPID",
    "2012": "PRICE_CONFIRMATION",
    "2040": "ORDER_MOD_IN",
    "2042": "ORDER_MOD_REJECT",
    "2061": "QUICK_CANCEL_OUT",
    "2062": "KILL_SWITCH_IN",
    "2070": "ORDER_CANCEL_IN",
    "2071": "ORDER_CANCEL_OUT",
    "2072": "ORDER_CANCEL_REJECT",
    "2073": "ORDER_CONFIRMATION",
    "2074": "ORDER_MOD_CONFIRMATION",
    "2075": "ORDER_CANCEL_CONFIRMATION",
    "2076": "CANCEL_NEG_ORDER",
    "2170": "FREEZE_TO_CONTROL",
    "2212": "ON_STOP_NOTIFICATION",
    "2222": "TRADE_CONFIRMATION",
    "2223": "TRADE_ERROR",
    "2231": "ORDER_ERROR",
    "2282": "TRADE_CANCEL_CONFIRM",
    "2286": "TRADE_CANCEL_REJECT",
    "2287": "TRADE_MODIFY_CONFIRM",
    "2300": "SIGN_ON_REQUEST_IN",
    "2301": "SIGN_ON_REQUEST_OUT",
    "2302": "ERROR_RESPONSE_OUT",
    "2321": "SIGN_OFF_REQUEST_OUT",
    "2400": "GR_REQUEST",
    "2401": "GR_RESPONSE",
    "5294": "BCAST_CONT_MSG",
    "5295": "CTRL_MSG_TO_TRADER",
    "5424": "USER_ADDR_UNLOCK_IN",
    "5425": "USER_ADDR_UNLOCK_OUT",
    "5440": "TRADE_CANCEL_IN",
    "5441": "TRADE_CANCEL_OUT",
    "5445": "TRADE_MOD_IN",
    "5575": "USER_ADDR_UNLOCK_APPROVE_OUT",
    "5579": "USER_ADDR_UNLOCK_REJECT_OUT",
    "5716": "BRANCH_ORDER_LIMIT_UPDATE_IN",
    "5717": "BRANCH_ORDER_LIMIT_UPDATE_OUT",
    "5719": "USER_ORDER_LIMIT_UPDATE_IN",
    "5720": "USER_ORDER_LIMIT_UPDATE_OUT",
    "5721": "DEALER_LIMIT_UPDATE_IN",
    "5722": "DEALER_LIMIT_UPDATE_OUT",
    "5723": "SIGN_OFF_TRADER_IN",
    "5724": "SIGN_OFF_TRADER_OUT",
    "5738": "RESET_PASSWORD_IN",
    "5739": "RESET_PASSWORD_OUT",
    "5790": "COL_USER_STATUS_CHANGE _IN",
    "5791": "COL_USER_STATUS_CHANGE _OUT",
    "5792": "TRD_MOD_CXL_STATUS_CHANGE _IN",
    "5793": "TRD_MOD_CXL_STATUS_CHANGE _OUT",
    "6501": "BCAST_JRNL_VCT_MSG",
    "6511": "BC_OPEN_MESSAGE",
    "6521": "BC_CLOSE_MESSAGE",
    "6531": "BC_PREOPEN_SHUTDOWN_MSG",
    "6541": "BC_CIRCUIT_CHECK",
    "6571": "BC_NORMAL_MKT_PREOPEN_ENDED",
    "6581": "BC_AUCTION_STATUS_CHANGE",
    "6582": "BCAST_AUCTION_INQUIRY_OUT",
    "7000": "DOWNLOAD_REQUEST",
    "7011": "HEADER_RECORD",
    "7021": "MESSAGE_RECORD",
    "7031": "TRAILER_RECORD",
    "7201": "BCAST_MW_ROUND_ROBIN",
    "7202": "BCAST_TICKER_AND_MKT_INDEX",
    "7206": "BCAST_SYSTEM_INFORMATION_OUT",
    "7210": "BCAST_SECURITY_STATUS_CHG_PREOPEN",
    "7214": "BCAST_CALL AUCTION_MBP",
    "7215": "BCAST_CA_MW",
    "7300": "UPDATE_LOCALDB_IN",
    "7304": "UPDATE_LOCALDB_DATA",
    "7305": "BCAST_SECURITY_MSTR_CHG",
    "7306": "BCAST_PART_MSTR_CHG",
    "7307": "UPDATE_LOCALDB_HEADER",
    "7308": "UPDATE_LOCALDB_TRAILER",
    "7320": "BCAST_SECURITY_STATUS_CHG",
    "7321": "PARTIAL_SYSTEM_INFORMATION",
    "7764": "BC_SYMBOL_STATUS_CHANGE_ACTION",
    "9002": "BATCH_ORDER_CANCEL",
    "9010": "BCAST_TURNOVER_EXCEEDED",
    "9011": "BROADCAST_BROKER_REACTIVATED",
    "18002": "MARKET_BY_ORDER_IN_TNDTC",
    "18003": "MARKET_BY_ORDER_OUT_TNDTC",
    "18016": "AUCTION_INQUIRY_IN_TNDTC",
    "18017": "AUCTION_INQUIRY_OUT_TNDTC",
    "18700": "BCAST_AUCTION_INQUIRY_OUT_TNDTC",
    "18701": "BROADCAST_MBO_MBP_TNDTC",
    "18702": "BCAST_MW_ROUND_ROBIN_TNDTC",
    "18703": "BCAST_TICKER_AND_MKT_INDEX_TNDTC",
    "18705": "BCAST_ONLY_MBP_TNDTC",
    "18707": "BCAST_SECURITY_STATUS_CHG_PREOPEN_TNDTC",
    "18708": "BCAST_BUY_BACK_TNDTC",
    "18710": "BCAST_CALL AUCTION_MBP_TNDTC",
    "18711": "BCAST_CA_MW_TNDTC",
    "18720": "BCAST_SECURITY_MSTR_CHG_TNDTC",
    "18130": "BCAST_SECURITY_STATUS_CHG_TNDTC",
    "20000": "BOARD_LOT_IN_TR",
    "20001": "BOARD_LOT_OUT_TR",
    "20040": "ORDER_MOD_IN_TR",
    "20041": "ORDER_MOD_OUT_TR",
    "20042": "ORDER_MOD_REJECT_TR",
    "20070": "ORDER_CANCEL_IN_TR",
    "20072": "ORDER_CANCEL_REJECT_TR",
    "20073": "ORDER_CONFIRMATION_TR",
    "20074": "ORDER_MOD_CONFIRMATION_TR",
    "20075": "ORDER_CXL_CONFIRMATION_TR",
    "20231": "ORDER_ERROR_TR",
    "20012": "PRICE_CONFIRMATION_TR",
    "20222": "TRADE_CONFIRMATION_TR",
    "23000": "BOX_SIGN_ON_REQUEST_IN",
    "23001": "BOX_SIGN_ON_REQUEST_OUT",
    "23008": "SECURE_BOX_REGISTRATION_REQUEST_IN",
    "23009": "SECURE_BOX_REGISTRATION_RESPONSE_OUT",
    "20322": "BOX_SIGN_OFF"
}

module.exports = {errdict, transdict};
